function result = montageToStack(montage, montageDims)
% MONTAGETOSTACK: Takes a montage and converts it back to a stack
% 
% Usage:
% result = montageToStack(montage, montageDims)
%
% Inputs:
% montage: a montage generated by stackToMontage or a modification of such
%  a montage
% montageDims: an output from stackToMontage specifying how many "tiles"
%  are in the montage in rows and columns, and how many z-slices to take
%  from the montage
%  montageDims(1) = numRows
%  montageDims(2) = numCols
%  montageDims(3) = zDim

mDim = size(montage,1) / montageDims(1);
nDim = size(montage,2) / montageDims(2);
cDim = size(montage,3);
zDim = montageDims(3);

result = zeros(mDim, nDim, cDim, zDim);
for i=1:zDim
    mPos = floor((i-1)/montageDims(2)); %starts at 0
    nPos = mod((i-1),montageDims(2)); %starts at 0
    result(:,:,:,i) = montage((1+mPos*mDim):(mDim*(mPos+1)), (1+nPos*nDim):(nDim*(nPos+1)), :);
end

% remove singleton dimensions (eg if cDim is 1)
result = squeeze(result);

end